"""MultiModelAnalyzer — Analyze and compare outputs from multiple vision models.

A solution-level component that wraps multiple model predictors, runs inference
on the same input, and produces comparative analysis reports.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import numpy as np
import torch


class MultiModelAnalyzer:
    """Analyze and compare outputs from multiple vision models.

    Provides tools for comparing detection/classification/segmentation outputs
    from different models to understand their agreement, disagreement, and
    complementary strengths.

    Args:
        models: List of model paths or identifiers to compare.
        device: Target device for inference.

    Example:
        >>> analyzer = MultiModelAnalyzer(
        ...     models=["flashdet-m.pt", "flashdet-l.pt", "flashdet-x.pt"],
        ...     device="cuda",
        ... )
        >>> report = analyzer.analyze("image.jpg")
        >>> print(report["agreement_score"])
    """

    def __init__(self, models: List[str], device: str = "auto"):
        self.model_paths = models
        self.device = self._resolve_device(device)
        self._results_cache: List[Dict[str, Any]] = []
        self._report: Optional[Dict[str, Any]] = None

    def analyze(self, image: Union[str, Path, np.ndarray]) -> Dict[str, Any]:
        """Run all models on an image and produce an analysis report.

        Args:
            image: Image path or numpy array (H, W, C) in BGR format.

        Returns:
            Dictionary containing per-model predictions and aggregate metrics:
                - per_model: list of per-model prediction dicts
                - agreement_score: float in [0, 1] measuring cross-model agreement
                - num_models: number of models compared
                - total_detections: sum of detections across models
                - avg_confidence: mean confidence across all predictions
        """
        per_model_outputs = self._run_inference(image)
        self._results_cache.append(per_model_outputs)

        agreement = self._compute_agreement(per_model_outputs)
        total_dets = sum(
            len(out.get("boxes", [])) for out in per_model_outputs
        )
        all_scores = []
        for out in per_model_outputs:
            scores = out.get("scores", [])
            if isinstance(scores, torch.Tensor):
                scores = scores.cpu().numpy().tolist()
            elif isinstance(scores, np.ndarray):
                scores = scores.tolist()
            all_scores.extend(scores)

        avg_conf = float(np.mean(all_scores)) if all_scores else 0.0

        self._report = {
            "per_model": per_model_outputs,
            "agreement_score": agreement,
            "num_models": len(self.model_paths),
            "total_detections": total_dets,
            "avg_confidence": avg_conf,
        }
        return self._report

    def compare_outputs(self, image: Union[str, Path, np.ndarray]) -> Dict[str, Any]:
        """Compare model outputs with detailed pairwise analysis.

        Args:
            image: Image path or numpy array.

        Returns:
            Dictionary with pairwise comparison metrics:
                - pairwise_iou: matrix of mean IoU between each model pair
                - detection_counts: number of detections per model
                - unique_detections: detections found by only one model
                - consensus_detections: detections found by all models
        """
        per_model_outputs = self._run_inference(image)
        num_models = len(per_model_outputs)

        detection_counts = [
            len(out.get("boxes", [])) for out in per_model_outputs
        ]

        pairwise_iou = np.zeros((num_models, num_models))
        for i in range(num_models):
            for j in range(num_models):
                if i == j:
                    pairwise_iou[i, j] = 1.0
                else:
                    pairwise_iou[i, j] = self._pairwise_agreement(
                        per_model_outputs[i], per_model_outputs[j]
                    )

        consensus = self._find_consensus_detections(per_model_outputs)
        unique = self._find_unique_detections(per_model_outputs)

        return {
            "pairwise_iou": pairwise_iou.tolist(),
            "detection_counts": detection_counts,
            "unique_detections": unique,
            "consensus_detections": consensus,
        }

    def get_report(self) -> Dict[str, Any]:
        """Return the most recent analysis report.

        Returns:
            The last report generated by analyze(), or an empty summary if
            no analysis has been run.
        """
        if self._report is not None:
            return self._report

        return {
            "per_model": [],
            "agreement_score": 0.0,
            "num_models": len(self.model_paths),
            "total_detections": 0,
            "avg_confidence": 0.0,
            "status": "no_analysis_run",
        }

    def reset(self) -> None:
        """Clear all cached results and reports."""
        self._results_cache.clear()
        self._report = None

    def _run_inference(self, image: Union[str, Path, np.ndarray]) -> List[Dict[str, Any]]:
        """Run inference with all models on the image.

        Returns:
            List of output dicts (one per model) containing 'boxes', 'scores', 'labels'.
        """
        outputs = []
        for model_path in self.model_paths:
            output = self._infer_single(model_path, image)
            outputs.append(output)
        return outputs

    def _infer_single(
        self, model_path: str, image: Union[str, Path, np.ndarray]
    ) -> Dict[str, Any]:
        """Run a single model on the image.

        For models without loaded weights this returns an empty prediction
        structure; with real model files it loads and runs inference.
        """
        path = Path(model_path)
        if path.exists() and path.suffix in (".pt", ".pth"):
            checkpoint = torch.load(str(path), map_location=self.device)
            if isinstance(checkpoint, dict) and "model" in checkpoint:
                model = checkpoint["model"]
            elif isinstance(checkpoint, torch.nn.Module):
                model = checkpoint
            else:
                return {"boxes": np.zeros((0, 4)), "scores": np.zeros(0), "labels": np.zeros(0, dtype=np.int64)}

            model.eval()
            model.to(self.device)
            img_tensor = self._preprocess(image)
            with torch.no_grad():
                output = model(img_tensor)
            return output if isinstance(output, dict) else {"raw": output}

        return {
            "boxes": np.zeros((0, 4)),
            "scores": np.zeros(0),
            "labels": np.zeros(0, dtype=np.int64),
        }

    def _preprocess(self, image: Union[str, Path, np.ndarray]) -> torch.Tensor:
        """Load and preprocess an image to a normalized tensor."""
        if isinstance(image, (str, Path)):
            import cv2
            img = cv2.imread(str(image))
            if img is None:
                raise FileNotFoundError(f"Cannot read image: {image}")
        else:
            img = image

        img = img.astype(np.float32) / 255.0
        img = np.transpose(img, (2, 0, 1))
        tensor = torch.from_numpy(img).unsqueeze(0).to(self.device)
        return tensor

    def _compute_agreement(self, outputs: List[Dict[str, Any]]) -> float:
        """Compute agreement score across all model outputs.

        Uses pairwise IoU matching to measure how much models agree.
        Returns a float in [0, 1].
        """
        if len(outputs) < 2:
            return 1.0

        scores = []
        for i in range(len(outputs)):
            for j in range(i + 1, len(outputs)):
                scores.append(self._pairwise_agreement(outputs[i], outputs[j]))

        return float(np.mean(scores)) if scores else 0.0

    def _pairwise_agreement(
        self, output_a: Dict[str, Any], output_b: Dict[str, Any]
    ) -> float:
        """Compute IoU-based agreement between two model outputs."""
        boxes_a = self._extract_boxes(output_a)
        boxes_b = self._extract_boxes(output_b)

        if len(boxes_a) == 0 and len(boxes_b) == 0:
            return 1.0
        if len(boxes_a) == 0 or len(boxes_b) == 0:
            return 0.0

        matched = 0
        used_b = set()
        for box_a in boxes_a:
            best_iou = 0.0
            best_idx = -1
            for idx_b, box_b in enumerate(boxes_b):
                if idx_b in used_b:
                    continue
                iou = self._compute_iou(box_a, box_b)
                if iou > best_iou:
                    best_iou = iou
                    best_idx = idx_b
            if best_iou > 0.5 and best_idx >= 0:
                matched += 1
                used_b.add(best_idx)

        total = max(len(boxes_a), len(boxes_b))
        return matched / total if total > 0 else 0.0

    def _find_consensus_detections(
        self, outputs: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Find detections that appear in all models."""
        if not outputs:
            return []

        base_boxes = self._extract_boxes(outputs[0])
        consensus = []

        for box in base_boxes:
            found_in_all = True
            for other_output in outputs[1:]:
                other_boxes = self._extract_boxes(other_output)
                has_match = any(
                    self._compute_iou(box, ob) > 0.5 for ob in other_boxes
                )
                if not has_match:
                    found_in_all = False
                    break
            if found_in_all:
                consensus.append({"box": box.tolist()})

        return consensus

    def _find_unique_detections(
        self, outputs: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Find detections that appear in only one model."""
        unique = []
        for model_idx, output in enumerate(outputs):
            boxes = self._extract_boxes(output)
            for box in boxes:
                found_elsewhere = False
                for other_idx, other_output in enumerate(outputs):
                    if other_idx == model_idx:
                        continue
                    other_boxes = self._extract_boxes(other_output)
                    if any(self._compute_iou(box, ob) > 0.5 for ob in other_boxes):
                        found_elsewhere = True
                        break
                if not found_elsewhere:
                    unique.append({"box": box.tolist(), "model_idx": model_idx})

        return unique

    @staticmethod
    def _extract_boxes(output: Dict[str, Any]) -> np.ndarray:
        """Extract boxes array from model output dict."""
        boxes = output.get("boxes", np.zeros((0, 4)))
        if isinstance(boxes, torch.Tensor):
            boxes = boxes.cpu().numpy()
        elif isinstance(boxes, list):
            boxes = np.array(boxes) if boxes else np.zeros((0, 4))
        return boxes

    @staticmethod
    def _compute_iou(box1: np.ndarray, box2: np.ndarray) -> float:
        """Compute IoU between two boxes in [x1, y1, x2, y2] format."""
        x1 = max(box1[0], box2[0])
        y1 = max(box1[1], box2[1])
        x2 = min(box1[2], box2[2])
        y2 = min(box1[3], box2[3])

        intersection = max(0, x2 - x1) * max(0, y2 - y1)
        area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])
        area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])
        union = area1 + area2 - intersection

        return float(intersection / max(union, 1e-6))

    @staticmethod
    def _resolve_device(device: str) -> torch.device:
        """Resolve device string to torch.device."""
        if device == "auto":
            return torch.device("cuda" if torch.cuda.is_available() else "cpu")
        return torch.device(device)

    def __repr__(self) -> str:
        return (
            f"MultiModelAnalyzer(models={len(self.model_paths)}, "
            f"device={self.device})"
        )
