version: "3.8"

services:
  flashfusion:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flashfusion
    volumes:
      - ../workspace:/app/workspace
      - ../data:/app/data
      - ../weights:/app/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
